// src/config/reown.ts
import { cookieStorage, createStorage } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { mainnet, arbitrum, polygon, optimism, base } from 'wagmi/chains'
import type { Chain } from 'viem'

// Read Project ID from environment variables (Astro uses import.meta.env)
export const projectId = import.meta.env.PUBLIC_WALLETCONNECT_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('PUBLIC_WALLETCONNECT_PROJECT_ID is not defined. Please set it in .env')
}

// Define supported networks, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [mainnet, arbitrum, polygon, optimism, base]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }), // Use cookieStorage for SSR
  ssr: true, // Enable SSR support
  projectId,
  networks, // Pass the explicitly typed networks array
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig
